name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install

    - name: Run test
      run: make test

    - name: Run format
      run: make format

    - name: Run lint
      run: make lint
